version: '3'
services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_DB: shortly_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres_db:5432/shortly_db
      JWT_SECRET: abc123
      PORT: 5000
    depends_on:
      - postgres_db
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - postgres_db
    networks:
      - app-network
    environment:
      VITE_API_URL: api

networks:
  app-network:
    driver: bridge


volumes:
  db_data: